#!/bin/sh
# mkguest.sh — compile the guest userland to rv64 and embed it as C arrays.
#
# The generated core/guestbin.h is COMMITTED, so building or shipping NOMINAL
# needs no riscv toolchain. Only changing a guest program does.
set -eu
OUT=core/guestbin.h
CC=${GUESTCC:-clang}
CFLAGS="--target=riscv64-unknown-elf -march=rv64im -mabi=lp64 -nostdlib
        -ffreestanding -fno-builtin -Os -Wall -Wextra -Iguest"

command -v "$CC" >/dev/null 2>&1 || { echo "mkguest: no $CC; keeping $OUT"; exit 0; }
command -v ld.lld >/dev/null 2>&1 || { echo "mkguest: no ld.lld; keeping $OUT"; exit 0; }

TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT
{
  echo "/* guestbin.h — GENERATED by tools/mkguest.sh. Do not edit."
  echo " *"
  echo " * The guest userland, compiled for our rv64 machine. These are real"
  echo " * programs: the boot loads them off the disk and executes them, and"
  echo " * corrupting one produces a genuine cpu trap or ELF-load failure."
  echo " */"
  echo "#ifndef NOM_GUESTBIN_H"
  echo "#define NOM_GUESTBIN_H"
  echo
} > "$TMP/h"

for p in init rc svcinit login sh ls cat ps ns pkg stat chmod; do
    # -Ttext keeps every program at a fixed load address: same layout every
    # run, on every host, which is one more thing determinism does not have
    # to be careful about.
    $CC $CFLAGS -fuse-ld=lld -Wl,-Ttext=0x10000 -Wl,--build-id=none \
        -o "$TMP/$p.elf" "guest/$p.c"
    python3 - "$TMP/$p.elf" "$p" >> "$TMP/h" <<'PY'
import sys
data = open(sys.argv[1], 'rb').read()
name = sys.argv[2]
print(f"static const unsigned char GUEST_{name.upper()}[] = {{")
for i in range(0, len(data), 12):
    print("    " + " ".join(f"0x{b:02x}," for b in data[i:i+12]))
print("};")
print(f"#define GUEST_{name.upper()}_LEN {len(data)}")
print()
PY
done

{ echo "#endif /* NOM_GUESTBIN_H */"; } >> "$TMP/h"
mv "$TMP/h" "$OUT"
echo "mkguest: wrote $OUT ($(wc -c < "$OUT") bytes)"
